<a href="https://colab.research.google.com/github/Aman-pr/journey/blob/main/Day27.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df=pd.read_csv('cars.csv')

In [ ]:
df

        brand  km_driven    fuel                 owner  selling_price
0      Maruti     145500  Diesel           First Owner         450000
1       Skoda     120000  Diesel          Second Owner         370000
2       Honda     140000  Petrol           Third Owner         158000
3     Hyundai     127000  Diesel           First Owner         225000
4      Maruti     120000  Petrol           First Owner         130000
...       ...        ...     ...                   ...            ...
8123  Hyundai     110000  Petrol           First Owner         320000
8124  Hyundai     119000  Diesel  Fourth & Above Owner         135000
8125   Maruti     120000  Diesel           First Owner         382000
8126     Tata      25000  Diesel           First Owner         290000
8127     Tata      25000  Diesel           First Owner         290000

[8128 rows x 5 columns]

In [ ]:
df['brand'].value_counts()

brand
Maruti           2448
Hyundai          1415
Mahindra          772
Tata              734
Toyota            488
Honda             467
Ford              397
Chevrolet         230
Renault           228
Volkswagen        186
BMW               120
Skoda             105
Nissan             81
Jaguar             71
Volvo              67
Datsun             65
Mercedes-Benz      54
Fiat               47
Audi               40
Lexus              34
Jeep               31
Mitsubishi         14
Land                6
Force               6
Isuzu               5
Ambassador          4
Kia                 4
MG                  3
Daewoo              3
Ashok               1
Opel                1
Peugeot             1
Name: count, dtype: int64

#1. OneHotEncoding using Pandas

In [ ]:
pd.get_dummies(df,columns=['fuel','owner'],dtype=int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,0,1,0,0,1,0,0,0,0
1,Skoda,120000,370000,0,1,0,0,0,0,1,0,0
2,Honda,140000,158000,0,0,0,1,0,0,0,0,1
3,Hyundai,127000,225000,0,1,0,0,1,0,0,0,0
4,Maruti,120000,130000,0,0,0,1,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,0,0,0,1,1,0,0,0,0
8124,Hyundai,119000,135000,0,1,0,0,0,1,0,0,0
8125,Maruti,120000,382000,0,1,0,0,1,0,0,0,0
8126,Tata,25000,290000,0,1,0,0,1,0,0,0,0
8127,Tata,25000,290000,0,1,0,0,1,0,0,0,0

#Droping the first row due to solving the problem of  multicollinearity

In [ ]:
df = pd.get_dummies(df, columns=['fuel', 'owner'], drop_first=True, dtype=int)

In [ ]:
pd.get_dummies(df,columns=['brand'],dtype=int)

,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner,brand_Ambassador,...,brand_Mitsubishi,brand_Nissan,brand_Opel,brand_Peugeot,brand_Renault,brand_Skoda,brand_Tata,brand_Toyota,brand_Volkswagen,brand_Volvo
0,145500,450000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,120000,370000,1,0,0,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,140000,158000,0,0,1,0,0,0,1,0,...,0,0,0,0,0,0,0,0,0,0
3,127000,225000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,120000,130000,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8123,110000,320000,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8124,119000,135000,1,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8125,120000,382000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8126,25000,290000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
8127,25000,290000,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

#2.OneHotEncoding using Sklearn

In [ ]:
df_2=pd.read_csv('cars.csv')

In [ ]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df_2.iloc[:,0:4],df_2.iloc[:,-1],test_size=0.2,random_state=2)

In [ ]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [ ]:
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',dtype=np.int32)

In [ ]:
X_train_new=ohe.fit_transform(X_train[['fuel','owner']]).toarray()
X_test_new=ohe.transform(X_test[['fuel','owner']]).toarray()

In [ ]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 0, 0, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 1, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 0, 0, 0]], dtype=int32)

In [ ]:
X_train_new.shape

(6502, 7)

In [ ]:
np.hstack((X_train[['brand','km_driven']].values,X_train_new))

array([['Hyundai', 35000, 1, ..., 0, 0, 0],
       ['Jeep', 60000, 1, ..., 0, 0, 0],
       ['Hyundai', 25000, 0, ..., 0, 0, 0],
       ...,
       ['Tata', 15000, 0, ..., 0, 0, 0],
       ['Maruti', 32500, 1, ..., 1, 0, 0],
       ['Isuzu', 121000, 1, ..., 0, 0, 0]], dtype=object)

#3.OneHotEncoding with Top Categories

In [ ]:
df_3=pd.read_csv('cars.csv')

In [ ]:
counts = df['brand'].value_counts()

In [ ]:
df['brand'].nunique()
threshold = 100

In [ ]:
repl = counts[counts <= threshold].index

In [ ]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
7453,False,False,False,False,True,False,False,False,False,False,False,False,False
3504,False,False,False,False,False,False,False,True,False,False,False,False,False
7297,False,False,False,False,True,False,False,False,False,False,False,False,False
4298,False,False,False,False,False,True,False,False,False,False,False,False,False
4812,False,True,False,False,False,False,False,False,False,False,False,False,False